### ISSUE TITLE
How about adding a parental guard service?

### ISSUE THREAD

**Issue by BiDuang** [RimoChan/python-anti-seduce-system#4]
I think if this program could adding a parental guard module, it can works better.

Write a function to check whether this program is running for the first time, and leave an email address. **When anyone tries to use command `python` to complie a file, it will trigger the mailer and warn parents that their children are trying to use python**, which is not allowed. XD

Have a nice day!

**Comment by RimoChan** [comment]
不行，这是「人防沉迷系统」，所以应该在人用Python的时候把邮件发送给狗！

**Comment by BiDuang** [comment]
雀食
那么就改成要求使用者在初次使用时留下“监护犬”的电子邮箱地址。
敬上
